### ISSUE TITLE
No support for Helm Requirements

### ISSUE THREAD

**Issue by jzelinskie** [app-registry/helm-plugin#3]
[Helm Requirements](https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/requirements.md) enable one Chart to depend on another. The Helm registry plugin doesn't currently support resolving these.

An example is [phpbb](https://github.com/kubernetes/charts/blob/master/stable/phpbb/requirements.yaml) which requires a MariaDB Chart.

**Comment by ant31** [comment]
cc @technosophos 
Do you have info for this issue ?

**Comment by technosophos** [comment]
I think the issue you'll want to look at is this: https://github.com/kubernetes/helm/pull/2094

**Comment by gtaylor** [comment]
@technosophos It looks like that upstream PR was merged. Does this mean that helm-plugin could do something like this? https://github.com/kubernetes/helm/pull/2094/files#diff-cfee875a1176f05d6d69d940ce4eba6f

**Comment by ant31** [comment]
@gtaylor I tried, it's working with `helm fetch` but it can't be use in a requirement.yaml yet.

**Comment by gtaylor** [comment]
> but it can't be use in a requirement.yaml yet.

To better understand where to look, is this a helm issue or an app-registry/helm-plugin issue?

**Comment by ant31** [comment]
a Helm issue: https://github.com/kubernetes/helm/issues/2447

**Comment by ant31** [comment]
Since the features is going to take more time to upstream it, it's going to be integrated into the plugin: 

it uses the `requirements.yaml` and a new key "appr" to list dependencies from the registry:

`$ cat requirements.yaml`
``` yaml 
# registry plugin dependencies
appr:
- name: quay.io/ant31/ghost
  repository: appr://
  version: '>=0.4.5'   # can use version queries

- name: quay.io/ant31/otherapp
  repository: appr://
  version: ':beta'   # can use channels ( :chan_name) 

# Upstream dependencies management:
dependencies:
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 0.6.0
```



1. Download packages from the app-registry server
```
$ helm registry dep --overwrite
Pulled package: quay.io/ant31/ghost (0.4.6-1) 
 -> dep_charts/ant31
```
The plugin rewrite the 'requirements.yaml' so it's now possible to use upstream dependency management:

2. Use helm dep:
```
$ helm dep build
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts

$ helm dep list
NAME      	VERSION	REPOSITORY                                       	STATUS
ghost     	0.4.5  	file://dep_charts/ant31/ghost                    	ok    
postgresql	0.6.0  	https://kubernetes-charts.storage.googleapis.com/	ok  
``` 

PR: https://github.com/app-registry/appr-cli/pull/23
